### ISSUE TITLE
Path format must be checked and validated.

### ISSUE THREAD

**Issue by mkorkmaz** [mkorkmaz/redislabs-rejson#1]

**Comment by aliozinan** [comment]
whatever path I set using the examples, it's ignored and db0 is being used. is the path related with db selection? seems like I can't select db1, db2 etc. even if I run after `$redisClient->connect( ... )` : 

`$redisClient->select(1)`

or 

`$redisClient->rawCommand("SELECT", "a:", 1, "a:");`

any updates on this?

**Comment by mkorkmaz** [comment]
Hi @aliozinan 

Basically redisjson-php just uses what redis clients provide. Selecting db should be done on redis client level if needed. So I don't expect any issue about it. But i should check in details whether redisjson module specifically uses db0. If I can find an answer I will let you know.

**Comment by aliozinan** [comment]
Hi @mkorkmaz ,

After reading the docs of ReJSON I understand that the paths have nothing to do with db selection.

However I just noticed that the solution to my issue was calling "pconnect" instead of "connect" from the PHPRedis lib like below : 

`$redisClient = new \Redis()->pconnect( HOST, PORT );`

only then I was able to select the db other than db0 & use your module : 

```
$redisClient->select(1);
$reJSON = ReJSON::createWithPhpRedis($redisClient);
...
```

I had installed RedisPHP using pecl as a side-note. I think this could be a useful tip on the readme of your repo. Thanks for the quick response.
